Repository risingwavelabs/risingwave-docs, pull requests merged in 2022-11, with the labels that each got.

#340 style: custom buttons
  docs/release-notes.md
  docusaurus.config.js
  src/css/buttons.css
  src/theme/DefaultButton/index.tsx
  src/theme/DefaultButton/style.css
  src/theme/LightButton/index.tsx
  src/theme/LightButton/style.css
  src/theme/MDXComponents/index.js
  src/theme/MDXComponents/styles.css
  src/theme/RollButton/index.tsx
  src/theme/RollButton/style.css
Labels: enhancement, website

#365 Fixing bugs in dev topics
  docs/deploy/risingwave-local.md
  docs/dev/java-client-libraries.md
  docs/dev/python-client-libraries.md
Labels: bug, documentation

#370 Adding the doc for datagen source connector
  docs/sql/commands/sql-create-source.md
  docs/sql/create-source/create-source-datagen.md
  src/css/custom.css
  src/theme/prism-sql.js
Labels: documentation
